language: common-lisp
sudo: required

before_install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - sudo pip install matplotlib

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl

script:
  - ros -s prove -e '(or (prove:run :matplotlib-cl-test) (uiop:quit -1))'
